### PR TITLE
feat(repositoryNames) Able to filter out what repos the Installation Token has access to via repo name

### PR DESCRIPTION
**Pull request by NickLiffen**
- Repo Name is now an option.

### CODE REVIEW

**Comment by NickLiffen** [comment]
@wolfy1339 & @gr2m no rush but when you get a chance I would love your thoughts on this pull request 👍 I welcome you to test/propose any changes 👍 I think it looks good and I have tried to make it match the style of this repository. However, welcome your feedback 💯

**Comment by NickLiffen** [comment]
Closes #277

**Comment by NickLiffen** [comment]
> This looks great so far, thank you Nick!
> 
> 3 things I'd suggest we add:
> 
> 1. I think I'd add a `(recommended)` to the `repositoryId` option.
>    One reason is that repository names can change, repository IDs cannot. If both are available, the user should use the ids.
>    Another reason is that the repository names or IDs (depending on what was passed) is used for caching IDs. Repository names can get long, repository ID lengths at least are predictable. This has an impact if e.g. Redis is used as a cache backend, but for widely used apps it could also impact memory usage.
> 2. Could you add a test where you set both, `repositoryIds` and `repositoryNames`, to see what happens, and to keep that behavior consistent?
> 3. Could you add to the descriptions in the README and typescript that either `repositoryIds` or `repositoryNames` should be set, not both? You can add TypeScript descriptions to options by adding a `/** comment herer */` above the option, I think

@gr2m 

1. I agree that `repositoryId` is a preferred input, I will make sure to add that 👍 

2. I will add a unit test 100% for that, good shout 👍 

3. Yes, I will add that, I think that's a good idea 👍 Do you think this module should opinionate any behaviour? Like only send the `repositoryIds` if both are present. Or, do you think we should leave that up to the API to make the decision. If that makes sense? I am happy to be flexible 👍  

I will make the changes first thing tomorrow (UK time) and send a PR your way after.

**Comment by gr2m** [comment]
> 3. Do you think this module should opinionate any behaviour? Like only send the `repositoryIds` if both are present. Or, do you think we should leave that up to the API to make the decision

When in doubt, I like to stay as close as possible to GitHub's APIs. Let's just pass it through and let GitHub's API respond with a helpful error.

**Comment by NickLiffen** [comment]
Sounds good @gr2m 👍 I have made the changes 👍  Appreciate the feedback 💯 Let me know if you have any more thoughts.

**Review by gr2m — APPROVED** [review]
Looks great, thanks a lot Nick!

**Pull request merged**
